CREATE TABLE IF NOT EXISTS raw.epa_sld (
    id           SERIAL PRIMARY KEY
    -- Geographic identifiers
    , OBJECTID   INTEGER
    , GEOID10    TEXT NOT NULL
    , GEOID20    TEXT
    , STATEFP    TEXT
    , COUNTYFP   TEXT
    , TRACTCE    TEXT
    , BLKGRPCE   TEXT
    , CSA        TEXT
    , CSA_Name   TEXT
    , CBSA       TEXT
    , CBSA_Name  TEXT
    -- Area context
    , CBSA_POP   DOUBLE PRECISION
    , CBSA_EMP   DOUBLE PRECISION
    , CBSA_WRK   DOUBLE PRECISION
    , Ac_Total   DOUBLE PRECISION
    , Ac_Water   DOUBLE PRECISION
    , Ac_Land    DOUBLE PRECISION
    , Ac_Unpr    DOUBLE PRECISION
    -- Population & housing
    , TotPop     INTEGER
    , CountHU    INTEGER
    , HH         INTEGER
    , P_WrkAge   DOUBLE PRECISION
    , AutoOwn0   INTEGER
    , Pct_AO0    DOUBLE PRECISION
    , AutoOwn1   INTEGER
    , Pct_AO1    DOUBLE PRECISION
    , AutoOwn2p  INTEGER
    , Pct_AO2p   DOUBLE PRECISION
    , Workers    INTEGER
    -- Employment by wage
    , R_LowWageWk  INTEGER
    , R_MedWageWk  INTEGER
    , R_HiWageWk   INTEGER
    , R_PCTLOWWAGE DOUBLE PRECISION
    -- Employment by type (5-category)
    , TotEmp     DOUBLE PRECISION
    , E5_Ret     DOUBLE PRECISION
    , E5_Off     DOUBLE PRECISION
    , E5_Ind     DOUBLE PRECISION
    , E5_Svc     DOUBLE PRECISION
    , E5_Ent     DOUBLE PRECISION
    -- Employment by type (8-category)
    , E8_Ret     DOUBLE PRECISION
    , E8_off     DOUBLE PRECISION
    , E8_Ind     DOUBLE PRECISION
    , E8_Svc     DOUBLE PRECISION
    , E8_Ent     DOUBLE PRECISION
    , E8_Ed      DOUBLE PRECISION
    , E8_Hlth    DOUBLE PRECISION
    , E8_Pub     DOUBLE PRECISION
    -- Employee wage
    , E_LowWageWk  INTEGER
    , E_MedWageWk  INTEGER
    , E_HiWageWk   INTEGER
    , E_PctLowWage DOUBLE PRECISION
    -- D1: Density
    , D1A        DOUBLE PRECISION
    , D1B        DOUBLE PRECISION
    , D1C        DOUBLE PRECISION
    , D1C5_RET   DOUBLE PRECISION
    , D1C5_OFF   DOUBLE PRECISION
    , D1C5_IND   DOUBLE PRECISION
    , D1C5_SVC   DOUBLE PRECISION
    , D1C5_ENT   DOUBLE PRECISION
    , D1C8_RET   DOUBLE PRECISION
    , D1C8_OFF   DOUBLE PRECISION
    , D1C8_IND   DOUBLE PRECISION
    , D1C8_SVC   DOUBLE PRECISION
    , D1C8_ENT   DOUBLE PRECISION
    , D1C8_ED    DOUBLE PRECISION
    , D1C8_HLTH  DOUBLE PRECISION
    , D1C8_PUB   DOUBLE PRECISION
    , D1D        DOUBLE PRECISION
    , D1_FLAG    INTEGER
    -- D2: Diversity
    , D2A_JPHH   DOUBLE PRECISION
    , D2B_E5MIX  DOUBLE PRECISION
    , D2B_E5MIXA DOUBLE PRECISION
    , D2B_E8MIX  DOUBLE PRECISION
    , D2B_E8MIXA DOUBLE PRECISION
    , D2A_EPHHM  DOUBLE PRECISION
    , D2C_TRPMX1 DOUBLE PRECISION
    , D2C_TRPMX2 DOUBLE PRECISION
    , D2C_TRIPEQ DOUBLE PRECISION
    , D2R_JOBPOP DOUBLE PRECISION
    , D2R_WRKEMP DOUBLE PRECISION
    , D2A_WRKEMP DOUBLE PRECISION
    , D2C_WREMLX DOUBLE PRECISION
    -- D3: Street design
    , D3A        DOUBLE PRECISION
    , D3AAO      DOUBLE PRECISION
    , D3AMM      DOUBLE PRECISION
    , D3APO      DOUBLE PRECISION
    , D3B        DOUBLE PRECISION
    , D3BAO      DOUBLE PRECISION
    , D3BMM3     DOUBLE PRECISION
    , D3BMM4     DOUBLE PRECISION
    , D3BPO3     DOUBLE PRECISION
    , D3BPO4     DOUBLE PRECISION
    -- D4: Transit access
    , D4A        DOUBLE PRECISION
    , D4B025     DOUBLE PRECISION
    , D4B050     DOUBLE PRECISION
    , D4C        DOUBLE PRECISION
    , D4D        DOUBLE PRECISION
    , D4E        DOUBLE PRECISION
    -- D5: Destination accessibility
    , D5AR       DOUBLE PRECISION
    , D5AE       DOUBLE PRECISION
    , D5BR       DOUBLE PRECISION
    , D5BE       DOUBLE PRECISION
    , D5CR       DOUBLE PRECISION
    , D5CRI      DOUBLE PRECISION
    , D5CE       DOUBLE PRECISION
    , D5CEI      DOUBLE PRECISION
    , D5DR       DOUBLE PRECISION
    , D5DRI      DOUBLE PRECISION
    , D5DE       DOUBLE PRECISION
    , D5DEI      DOUBLE PRECISION
    -- Composite scores
    , D2A_Ranked DOUBLE PRECISION
    , D2B_Ranked DOUBLE PRECISION
    , D3B_Ranked DOUBLE PRECISION
    , D4A_Ranked DOUBLE PRECISION
    , NatWalkInd DOUBLE PRECISION
    -- Geometry
    , Shape_Length DOUBLE PRECISION
    , Shape_Area   DOUBLE PRECISION
    , UNIQUE (GEOID10)
);
